name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # daily update (UTC midnight)
  workflow_dispatch:      # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Nightkilller
          THEME: 2077
